development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  database: themes_dev

test:
  <<: *default
  database: themes_test

production:
  <<: *default
  database: themes